### ISSUE TITLE
IndexedFiles with quoted field containing linebreaks results in fileTailParts being added within field content

### ISSUE THREAD

**Issue by Hutchenson** [simoc/csvjdbc#120]
Hi,

we are having an issues with loading a file in combination of indexedFiles with fileTailParts and quoted content containing line breaks option on latest driver version (1.0.42). 

It looks like it is doing what is documented (fileTailParts are added to each new line) - but in this configuration I wouldn't expect it to add it to the quoted multiline field content. 
Basically it leads to a field content containing the fileTailParts added on each line.

![image](https://github.com/user-attachments/assets/15abd3c6-2632-43e9-8169-f74443be7a9f)

Workaround: Unknown.

To reproduce:

fileExtension=.txt
fileTailParts=date
fileTailPattern=_(\d+)
indexedFiles=true
quotechar="
suppressHeaders=false
[Sample_011020182.txt](https://github.com/user-attachments/files/16613973/Sample_011020182.txt)

Is there something wrong with the above configuration or is it a bug? Please let me know if we can support here with further analysis & fix.

Best regards

**Comment by simoc** [comment]
Thank you for the clear description.

This is a bug in CsvJdbc.

I suppose that no one tried this combination before (IndexedFiles and fields with line breaks).

I will check next week, whether it is possible to solve this bug.

**Comment by simoc** [comment]
This problem is fixed in Csvjdbc version 1.0.43.
