### ISSUE TITLE
Provide a primary key 'LINENUM' or similar

### ISSUE THREAD

**Issue by geert3** [simoc/csvjdbc#14]
It would be nice if tables implicitly had a primary key column that reflects the line number of the current row.
That column could be use in SELECT clause, e.g. 
    SELECT LINENUM, * FROM ...
or in WHERE clause, e.g.
    SELECT * FROM ... WHERE LINENUM > 100

**Comment by simoc** [comment]
CsvJdbc has the SQL keywords OFFSET and LIMIT for limiting the number of records returned by a query.

If you need something more advanced, then I suggest using a real RDBMS such as PostgreSQL.

**Comment by geert3** [comment]
OFFSET and LIMIT are useful to reduce the selection based on line numbers. Actually querying the line number is not trivial but possible by creating one's own Reader class (jdbc:relique:csv:class:MyReader) and inserting the line number into the records there. A more built-in approach would be great though.
