### ISSUE TITLE
source file without license header

### ISSUE THREAD

**Issue by puntogil** [simoc/csvjdbc#2]
Hi
The following source file is without license header:
./src/main/java/org/relique/jdbc/csv/SQLSubstringFunction.java
Please, add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
Thanks in advance
Regards

**Comment by simoc** [comment]
Fixed in commit d76be8815268f83970f908f71326f027bfa0fee5
