### ISSUE TITLE
qStudio uses CSVJDBC

### ISSUE THREAD

**Issue by ryanhamilton** [simoc/csvjdbc#68]
Hi,

Just wanted to say thanks for this library.  That I've added it as a JDBC driver within qStudio:
https://www.timestored.com/qstudio/help/connections/csvjdbc

Very useful for my own testing :)

Thanks,
Ryan

**Comment by simoc** [comment]
Glad you found Csvjdbc useful -- replacing a real database for testing is one of the things that Csvjdbc is good for.

Closing this issue.
