### ISSUE TITLE
CsvResultSet.getArray throws UnsupportedOperationException

### ISSUE THREAD

**Issue by PeterFokkinga** [simoc/csvjdbc#70]
The CsvResultSet.getArray methods currently throw an UnsupportedOperationException. This makes dealing with array output (from a custom function) cumbersome.

Background: 
We have a simple ETL tool that uses SQL scripts to fetch data from sources to import into several databases. CsvJDBC is used to keep the ETL logic in SQL when dealing with CSV and XML (through an XML -> CSV converter that extends `Reader`); it's brilliant because it allows us to keep the code generic whether dealing with imports from databases or files. However, some of the target (PostgreSQL) databases have columns of type array that we cannot load from CSV unless we make special checks to see if the source is CSV which is ugly and adds to maintenance.

Proposal:
1. have `getArray` return the result of `getObject` cast to `java.sql.Array` when it is an instance of Array or throw an exception when it is not
2. provide a simple implementation of the `Array` interface (implementing its getArray methods, not the getResultSet methods) to facilitate writing functions returning an array
3. add a `TO_ARRAY([DISTINCT] N1, N2, ...)` function  for demonstration / convenience
4. add an aggregate function `ARRAY_AGG([DISTINCT S)`  for demonstration / convenience

If you feel this is a worthwhile addition to the CsvJDBC mainline then I can provide a pull request shortly.

**Comment by simoc** [comment]
Yes, I will accept a Pull Request to add support for array data types to CsvJdbc.

**Comment by simoc** [comment]
These changes are included in Csvjdbc version 1.0.41.

**Comment by PeterFokkinga** [comment]
thanks, much appreciated @simoc !
