### ISSUE TITLE
Charset not applied onto indexed fileTailPattern result and fileTailParts

### ISSUE THREAD

**Issue by Hutchenson** [simoc/csvjdbc#8]
Hi,

we are having an issues with loading a file encoded in UTF-16LE in combination with the indexedFiles option on latest driver version (1.0.36). It looks like it is not encoding the header&content of the additional columns in the specified charset (UTF-16LE) too, leading to some cryptic content being attached to the last column instead of adding an additional column.

![image](https://user-images.githubusercontent.com/27774211/97980990-e9094000-1dd1-11eb-8f09-631886ec8949.png)

When converting the file into UTF8 it works fine.

To reproduce:
charset=UTF-16LE
fileExtension=.txt
fileTailParts=date
fileTailPattern=\_(\d+)
indexedFiles=true
quotechar="
separator=|
suppressHeaders=false
[Sample_01102018.txt](https://github.com/simoc/csvjdbc/files/5480950/Sample_01102018.txt)

Is there something wrong with the above configuration or is it a bug? Please let me know if we can support here with further analysis & fix.

Best regards

**Comment by simoc** [comment]
I downloaded attachment Sample_01102018.txt and it was a plain ASCII file. I converted this file to UTF-16LE encoding using the command:

iconv -f UTF-8 -t UTF-16LE < Sample_01102018.txt > Foo_1102018.txt

[Foo_01102018.txt](https://github.com/simoc/csvjdbc/files/5483239/Foo_01102018.txt)

**Comment by simoc** [comment]
I reproduced this problem in CsvJdbc.

I think the bug is in CsvJdbc method `org.relique.io.FileSetInputStream.read()`. This function only handles single byte carriage return 0x0D and newline 0x0A characters and not the 0x0D00 and 0x0A00 two-byte values for UTF-16LE.
