### ISSUE TITLE
Add `ORDER BY RANDOM()` support 

### ISSUE THREAD

**Issue by DeflateAwning** [simoc/csvjdbc#88]
Would be awesome if you could sort the rows randomly with a query. 

Related to [this DBeaver issue](https://github.com/dbeaver/dbeaver/issues/21831)

### Implementation Comments
This syntax technically means "generate a random number for each row, and then sort the rows" (which uses `O(n)` where `n` is the number of rows in the table, depending on the sort algo). As we implement it here though, we should try to use a more efficient algorithmn which doesn't require generating a number for every row in the table, but rather selects a random row number from the table on repeat until it hits the `LIMIT`/`TOP` count condition.

**Comment by simoc** [comment]
`ORDER BY RANDOM()` is currently not possible with CsvJdbc.

I will add this functionality in the coming weeks.

**Comment by simoc** [comment]
These changes are included in Csvjdbc version 1.0.42.
